### ISSUE TITLE
Clarification sur le sujet

### ISSUE THREAD

**Issue by HirwaShemaLin** [SebastianGrandaA/BatchPicking#1]
Merci pour l'accès au git et au rapport à l'état présent.

Vu que c'est un rapport intermédiaire, je ne m'attend pas à ce que les approches et modèles soient complets à l'instant.
 Je veux surtout m'assurer que le sujet a bien été compris. Dans ce but, j'aimerai clarifier quelques points du sujet sur lesquels il y a possiblement un malentendu:

-  2 supports peuvent avoir des positions en commun, et toutes les positions d'un support doivent être visitées dans la tournée du batch associé à ce support.
-   Il n'y a pas de contrainte sur la quantité d'articles/produits dans un batch. Seule la quantité de supports et la somme des volumes des supports limitent un batch.

Si ceci est bien pris en compte, vous pouvez ignorer cette issue.

Bon courage à vous ;)

**Comment by SebastianGrandaA** [comment]
Salut @HirwaShemaLin ! Merci beaucoup pour votre retour. En effet, nous avons considéré les points précités de la manière suivante :

1. Étant donné que plusieurs commandes peuvent avoir des positions communes, nous modélisons les items sous forme de nœuds, chacun étant associé à une position.
2. De même, toutes les positions doivent être visitées dans la tournée du batch, mais il est possible d'alterner les positions entre les commandes d'un même batch si cela implique une distance plus courte.
3. Les items par commande étant fixes, nous nous limitons au nombre de commandes (supports) par batch - complétant la capacité en volume.

Ces points sont mieux détaillés dans les hypothèses du problème.

**Comment by HirwaShemaLin** [comment]
Pour être plus précis:

- à la contrainte (3) de votre modèle, vous contraignez que chaque article soit collecté dans un seul batch alors qu'il devrait être possible que 2 commandes qui ont des articles en commun soient dans différents batchs.

- à la contrainte (7) vous utiliser `q_r` pour limiter les batchs alors que vous avez définit `q_r` comme étant la quantité d'articles dans un support `r`. Ceci n'est pas la contrainte. La contrainte est de limiter la quantité de supports dans un batch, pas la quantité d'articles. De plus q_r et v_r sont indicés sur les nœuds dans le modèle alors que ces valeurs sont définies pour les supports.

Surtout vérifiez que les solutions retournés par vos modèles et algos passent le checker fournit, parce que ça risque d'être irréalisable sinon.

**Comment by SebastianGrandaA** [comment]
1. Oui, mais si deux articles à la même position appartiennent à des ordres différents, alors ce sont deux nœuds dans le graphe. Donc, on peut contraindre les sommets à être assignés à un seul batch.
2. Concernant la restriction (7), en effet, nous avons corrigé le fait qu'elle restreint le nombre d'éléments (q_r). Cependant, dans la mise en œuvre, nous utilisons la formulation séquentielle. La formulation jointe pourrait en outre être utilisée pour obtenir une borne inférieure sur la distance totale.

**Comment by HirwaShemaLin** [comment]
1. Du coup il faudrait expliquer ceci clairement dans le rapport, ainsi que comment vous construisez le graphe vu qu'il y a des nœuds en plus par rapport à la matrice d'adjacence.
2. Même si vous n'implémentez pas le modèle, faudra tout de même s'assurer que toutes les contraintes sont bonnes.

Bonne continuation!
